# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablero.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 442)
        
        #screen_geometry = QtWidgets.QDesktopWidget().screenGeometry()

        screen_geometry = QtWidgets.QDesktopWidget().availableGeometry()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ka = QtWidgets.QLabel(self.centralwidget)
        self.ka.setGeometry(screen_geometry)
        self.ka.setText("")
        self.ka.setPixmap(QtGui.QPixmap("aj.jpg"))
        self.ka.setObjectName("ka")
        self.bo = QtWidgets.QLabel(self.centralwidget)
        self.bo.setGeometry(screen_geometry)
        self.bo.setText("")
        self.bo.setPixmap(QtGui.QPixmap("aj2.jpg"))
        self.bo.setObjectName("bo")

        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(screen_geometry.width()-190, 400, 75*2, 23*2))
        self.plus.setObjectName("plus")

        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(screen_geometry.width()-190, 600, 75*2, 23*2))
        self.minus.setObjectName("minus")

        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(screen_geometry.width()-190, 100, 150, 50))
        self.pushButton2.setObjectName("pushButton2")
     
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(screen_geometry.width()-190, 500, 64*2, 23*2))
        self.lcdNumber.setObjectName("lcdNumber")
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.button_count = 150

        self.lcdNumber.display(self.button_count)
        self.plus.clicked.connect(self.clicked)
        self.minus.clicked.connect(self.clicked2)
        self.pushButton2.clicked.connect(self.start)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.pushButton2.setText(_translate("MainWindow", "Start"))

    def enabled(self):
        current_state = self.bo.isVisible()
        self.bo.setVisible(not current_state)
        print("paso por enabled", current_state)     
        
    def start(self):
        freq = 1000
        if self.button_count>0:
            self.timerA = QtCore.QTimer()
            self.timerA.timeout.connect(self.enabled)
            self.timerA.start(freq)
            print("entro a start")
            self.button_count -= 1

        else:
            print("ya ta")
    
    def clicked(self):
        self.button_count += 25
        print(self.button_count)
        self.lcdNumber.display(self.button_count)

    def clicked2(self):
        self.button_count -= 25
        print(self.button_count)
        self.lcdNumber.display(self.button_count)

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Escape or event.key() == QtCore.Qt.Key_Space:
            self.showNormal()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
      
    window.showFullScreen()
    app.installEventFilter(window)
    sys.exit(app.exec_())
